dist: trusty
sudo: required
language: cpp

compiler:
  - gcc
  - clang

script:
  - sudo apt update
  - sudo apt upgrade
  - sudo apt-get install libsdl2-dev
  - dpkg --get-selections | grep hold
  - mkdir build
  - cd build
  - cmake ..
  - make

