dist: trusty
sudo: required
language: cpp

compiler:
  - gcc

before_install:
- sudo add-apt-repository -y ppa:team-xbmc/ppa
- sudo apt-get update -qq
- sudo apt-get install -y  libsdl2-dev

notifications:
  email: false

script:
  - mkdir build
  - cd build
  - cmake ..
  - make

