dist: trusty
sudo: required
language: cpp

compiler:
  - gcc
  - clang

script:
  - sudo apt-get install libsndio-dev
  - sudo apt-get install libegl1-mesa-dev
  - sudo apt-get install libgles2-mesa-dev
  - sudo apt-get install libsdl2-dev
  - mkdir build
  - cd build
  - cmake ..
  - make

